services:
  postgres:
    container_name: postgres-sql-lms
    image: library
    environment:
      POSTGRES_USER : username
      POSTGRES_PASSWORD : password
      PGDATA : /var/lib/postgresql/data
      POSTGRES_DB : library_management_system
    volumes:
      - library:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-library
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  library:
    driver: local